### ISSUE TITLE
运行提示出错

### ISSUE THREAD

**Issue by largesun** [itliuwk/newretail-admin-web#1]
你好，
src/router文件夹下是不是少了index.js
运行出现下面错误：

ERROR  Failed to compile with 3 errors                                                                                     01:07:57

This dependency was not found:
* @/router in ./src/store/modules/app.js
To install it, you can run: npm install --save @/router

This relative module was not found:
* ./router in ./src/main.js, ./src/permission.js

**Comment by itliuwk** [comment]
问题已解决   原因是 router 文件夹确实入口 index.js

**Comment by gunnimei** [comment]
你好，为什么下载依赖会报错

**Comment by mokiki1** [comment]
您好，依赖下载报错是什么原因啊

**Comment by quchengbin** [comment]
这里面用到了Python为什么没有标注
