### ISSUE TITLE
运行出错 @/utils/upload

### ISSUE THREAD

**Issue by kiracookie** [itliuwk/newretail-admin-web#4]
嗨~，
运行报错，翻了src/utils/下 确实没有upload
是不是新加了组件有文件没有上传？
This dependency was not found:

* @/utils/upload in ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.0.6@babel-loader/lib!./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.2@vue-loader/lib??vue-loader-options!./src/views/advertisingManagement/materialManagement/pictureComponents.vue?vue&type=script&lang=js&, ./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--12-0!./node_modules/_babel-loader@8.0.6@babel-loader/lib!./node_modules/_cache-loader@2.0.1@cache-loader/dist/cjs.js??ref--0-0!./node_modules/_vue-loader@15.7.2@vue-loader/lib??vue-loader-options!./src/views/advertisingManagement/materialManagement/videoComponents.vue?vue&type=script&lang=js& and 3 others

To install it, you can run: npm install --save @/utils/upload

**Comment by itliuwk** [comment]
自己可以新建  upload.js  文件   放在 utils 下， 因为这个upload.js不是个人私有的，是用到七牛云的token那些，已提交  upload.js  文件
